// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api_29_07_Mine.Context;

#nullable disable

namespace Web_Api_29_07_Mine.Migrations
{
    [DbContext(typeof(MinecraftContext))]
    [Migration("20260805112816_AddMinecraftEntities")]
    partial class AddMinecraftEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Bioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Chove")
                        .HasColumnType("bit");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Biomas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chove = true,
                            Nome = "Plains",
                            Temperatura = 0.80000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Chove = false,
                            Nome = "Desert",
                            Temperatura = 2.0
                        },
                        new
                        {
                            Id = 3,
                            Chove = true,
                            Nome = "Forest",
                            Temperatura = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Empilhavel")
                        .HasColumnType("bit");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Resistencia")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blocos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Empilhavel = true,
                            Nome = "Diamond Block",
                            Resistencia = 5.0,
                            Tipo = "Mineral"
                        },
                        new
                        {
                            Id = 2,
                            Empilhavel = true,
                            Nome = "Stone",
                            Resistencia = 1.5,
                            Tipo = "Natural"
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Encantamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelMaximo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Encantamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Sword",
                            Descricao = "Aumenta o dano da espada.",
                            NivelMaximo = 5,
                            Nome = "Sharpness"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Tool",
                            Descricao = "Aumenta a velocidade de mineração.",
                            NivelMaximo = 5,
                            Nome = "Efficiency"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Pickaxe",
                            Descricao = "Aumenta a quantidade de drops.",
                            NivelMaximo = 3,
                            Nome = "Fortune"
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Inventario", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            ItemId = 1,
                            Quantidade = 1
                        },
                        new
                        {
                            PlayerId = 1,
                            ItemId = 2,
                            Quantidade = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            ItemId = 3,
                            Quantidade = 5
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagemUrl = "https://minecraft.wiki/images/Diamond_Sword.png",
                            Nome = "Diamond Sword",
                            Tipo = "Weapon"
                        },
                        new
                        {
                            Id = 2,
                            ImagemUrl = "https://minecraft.wiki/images/Diamond_Pickaxe.png",
                            Nome = "Diamond Pickaxe",
                            Tipo = "Tool"
                        },
                        new
                        {
                            Id = 3,
                            ImagemUrl = "https://minecraft.wiki/images/Golden_Apple.png",
                            Nome = "Golden Apple",
                            Tipo = "Food"
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Mob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hostil")
                        .HasColumnType("bit");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bioma = "Plains",
                            Drop = "Gunpowder",
                            Hostil = true,
                            Nome = "Creeper",
                            Vida = 20
                        },
                        new
                        {
                            Id = 2,
                            Bioma = "Forest",
                            Drop = "Rotten Flesh",
                            Hostil = true,
                            Nome = "Zombie",
                            Vida = 20
                        },
                        new
                        {
                            Id = 3,
                            Bioma = "Plains",
                            Drop = "Leather",
                            Hostil = false,
                            Nome = "Cow",
                            Vida = 10
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Mundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mundos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bioma = "Plains",
                            Nome = "Survival"
                        },
                        new
                        {
                            Id = 2,
                            Bioma = "Forest",
                            Nome = "Creative"
                        },
                        new
                        {
                            Id = 3,
                            Bioma = "Desert",
                            Nome = "Hardcore"
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MundoId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("SkinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MundoId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MundoId = 1,
                            Nickname = "Steve",
                            Nivel = 35,
                            SkinUrl = "https://crafatar.com/avatars/Steve",
                            Uuid = "uuid-steve"
                        },
                        new
                        {
                            Id = 2,
                            MundoId = 2,
                            Nickname = "Alex",
                            Nivel = 18,
                            SkinUrl = "https://crafatar.com/avatars/Alex",
                            Uuid = "uuid-alex"
                        });
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Inventario", b =>
                {
                    b.HasOne("Web_Api_29_07_Mine.Models.Item", "Item")
                        .WithMany("Inventarios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api_29_07_Mine.Models.Player", "Player")
                        .WithMany("Inventarios")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Player", b =>
                {
                    b.HasOne("Web_Api_29_07_Mine.Models.Mundo", "Mundo")
                        .WithMany("Players")
                        .HasForeignKey("MundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mundo");
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Item", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Mundo", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Web_Api_29_07_Mine.Models.Player", b =>
                {
                    b.Navigation("Inventarios");
                });
#pragma warning restore 612, 618
        }
    }
}
